spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        order_inserts: true
        dialect: org.hibernate.dialect.OracleDialect
        jdbc:
          batch_size: 50
          lob:
            non_contextual_creation: true
        default_schema: ${D_USERNAME}
        temp:
          use_jdbc_metadata_defaults: false

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      idle-timeout: 10000
      maximum-pool-size: 5
    driver-class-name: oracle.jdbc.driver.OracleDriver

logging:
  level:
    root: DEBUG
    org.springframework: DEBUG