# Server properties
server:
  servlet:
    context-path: /ssmu-api
  port: application-dev.yml"
  
# Spring properties
spring:
  # Dev is active by default. This value can be overwritten by java arg param
  profiles:
    active: ${PROFILE}
  application:
    name: ssmu-api # Same as context-path
